version: '3.8'

services:
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - PORT=3000
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - PORT=3000
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"

  nginx:
    image: nginx:latest
    container_name: nginx_router
    ports:
      - "8080:80"
    depends_on:
      - app_blue
      - app_green
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d-empty:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx    # <-- new shared log mount  
    env_file:
      - .env
